/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thalmic_myo_Myo */

#ifndef _Included_com_thalmic_myo_Myo
#define _Included_com_thalmic_myo_Myo
#ifdef __cplusplus
extern "C" {
#endif
#undef com_thalmic_myo_Myo_VIB_SHORT
#define com_thalmic_myo_Myo_VIB_SHORT 0L
#undef com_thalmic_myo_Myo_VIB_MEDIUM
#define com_thalmic_myo_Myo_VIB_MEDIUM 1L
#undef com_thalmic_myo_Myo_VIB_LONG
#define com_thalmic_myo_Myo_VIB_LONG 2L
#undef com_thalmic_myo_Myo_UT_TIMED
#define com_thalmic_myo_Myo_UT_TIMED 0L
#undef com_thalmic_myo_Myo_UT_HOLD
#define com_thalmic_myo_Myo_UT_HOLD 1L
#undef com_thalmic_myo_Myo_SET_DISABLED
#define com_thalmic_myo_Myo_SET_DISABLED 0L
#undef com_thalmic_myo_Myo_SET_ENABLED
#define com_thalmic_myo_Myo_SET_ENABLED 1L
/*
 * Class:     com_thalmic_myo_Myo
 * Method:    _vibrate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo__1vibrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    _requestRssi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo__1requestRssi
  (JNIEnv *, jobject);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    _requestBattLevel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo__1requestBattLevel
  (JNIEnv *, jobject);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    _unlock
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo__1unlock
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    _lock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo__1lock
  (JNIEnv *, jobject);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    _notifyAction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo__1notifyAction
  (JNIEnv *, jobject);

/*
 * Class:     com_thalmic_myo_Myo
 * Method:    _setStreamEmg
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thalmic_myo_Myo__1setStreamEmg
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
